# STAGE 1: Build
FROM node:lts-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/web/package.json ./apps/web/
# COPY packages/api-contract/package.json ./packages/api-contract/

RUN pnpm install --frozen-lockfile

COPY apps/web ./apps/web
# COPY packages/api-contract ./packages/api-contract
COPY turbo.json .

RUN pnpm turbo build --filter=web...

# STAGE 2: Serve
FROM nginx:stable-alpine
# Copy our custom config
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
# Copy static files from builder
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]